name: Run tests

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    tests:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                php: [8.2, 8.3, 8.4]

        name: ${{ matrix.os }} - PHP ${{ matrix.php }}

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: posix, dom, curl, libxml, fileinfo, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none

            - name: Install dependencies
              run: composer update --prefer-stable --prefer-dist --no-interaction --ignore-platform-req=ext-pcntl --ignore-platform-req=ext-posix

            - name: Run tests
              run: vendor/bin/phpunit

            - name: Send Slack notification
              uses: 8398a7/action-slack@v3
              if: failure()
              with:
                  status: ${{ job.status }}
                  fields: repo,message,author,action,eventName # selectable (default: repo,message)
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
